core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/UuidItemImpl.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/IUuidItemTest.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/IWritingContext.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/json/MetaschemaJsonWriter.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/codegen/AbstractMetaschemaTest.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/codegen/BasicMetaschemaTest.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/io/json/JsonParserTest.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/model/DefaultAssemblyClassBindingTest.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/CLI.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/AbstractConvertSubcommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/AbstractValidateContentCommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/GenerateSchemaCommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/ValidateContentUsingModuleCommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/ValidateModuleCommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/metapath/ListFunctionsSubcommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/metapath/MetapathCommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/util/LoggingValidationHandler.java, metaschema-cli/src/test/java/gov/nist/secauto/metaschema/cli/CLITest.java, metaschema-maven-plugin/src/main/java/gov/nist/secauto/metaschema/maven/plugin/AbstractMetaschemaMojo.java, metaschema-maven-plugin/src/main/java/gov/nist/secauto/metaschema/maven/plugin/GenerateSchemaMojo.java, metaschema-maven-plugin/src/main/java/gov/nist/secauto/metaschema/maven/plugin/GenerateSourcesMojo.java, metaschema-testing/src/main/java/gov/nist/secauto/metaschema/model/testing/AbstractTestSuite.java, schemagen/src/test/java/gov/nist/secauto/metaschema/schemagen/AbstractSchemaGeneratorTestSuite.java, schemagen/src/test/java/gov/nist/secauto/metaschema/schemagen/JsonSuiteTest.java, schemagen/src/test/java/gov/nist/secauto/metaschema/schemagen/XmlSuiteTest.java
Cleaned up a bunch of checkstyle and compile warnings.
Added Javadocs for many methods.
=> Code cleanup and Javadocs

databind-metaschema/pom.xml, databind-metaschema/src/main/java/gov/nist/secauto/metaschema/modules/sarif/SarifValidationHandler.java, databind-metaschema/src/test/java/gov/nist/secauto/metaschema/modules/sarif/SarifValidationHandlerTest.java
This PR adds support for SARIF help-url, help-text, and help-markdown for rule entries.
This PR also relocates use of the SARIF module to its new location in https://github.com/metaschema-framework/metaschema-modules/tree/main/sarif.
Resolves #131
=> Add support for SARIF help URLs, text, and markdown

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/DefaultFunction.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/IFunction.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/InvalidTypeFunctionException.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnString.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/impl/AbstractArrayItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/impl/AbstractMapItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/function/IArrayItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/function/IMapItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/AssemblyGlobalDefinitionNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/AssemblyInstanceNoValueNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/AssemblyInstanceNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/AssemblyOrphanedDefinitionDataNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/AssemblyOrphanedDefinitionNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/CycledAssemblyInstanceNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/DocumentNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/FieldGlobalDefinitionNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/FieldInstanceNoValueNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/FieldInstanceNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/FieldOrphanedDefinitionNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/FlagGlobalDefinitionNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/FlagInstanceNoValueNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/FlagInstanceNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/INodeItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/ModuleNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/RootAssemblyValuedNodeItemImpl.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnStringTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FunctionTestBase.java
Added support for the [fn:string](https://www.w3.org/TR/xpath-functions-31/#func-string) Metapath functions.
In support of this, added a stringValue method to INodeItem implementations to get the string value of it's contents. 
Resolves #122
=> Implement fn:string Metapath function

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnMatches.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnTokenize.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/regex/RegexUtil.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/regex/RegularExpressionMetapathException.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/AbstractStringItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/IStringItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/UuidItemImpl.java, core/src/main/java/module-info.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnMatchesTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnTokenizeTest.java
Adds support for the Metapath string functions that handle [regular expression operations](https://www.w3.org/TR/xpath-functions-31/#string.match).
- [~~fn:replace~~](https://www.w3.org/TR/xpath-functions-31/#func-replace)
Resolves #134
Resolves #135
=> Implement Metapath regex functions

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/DynamicContext.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/StringLiteral.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/DefaultFunction.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnNormalizeSpace.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnString.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/AbstractStringItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/IStringItem.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/ExpressionTestBase.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnFalseTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnNormalizeSpaceTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnStringTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnTrueTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FunctionTestBase.java, pom.xml
- Added support for the normalize-space Metapath function.
- Also fixed a bug in the string literal handling that inconsistently caused leading and trailing quotes to be removed. 
- Also fixed an issue with the build that was causing surefire to inconsistently handle a JUnit extension.
Resolves #133
=> Support the normalize-space Metapath function

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnSubstring.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnSubstringTest.java, pom.xml
This PR adds `fn:substring`, 1 of 3 to be added as part of work for #132.
=> Add `fn:substring` to Metapath function library

databind/src/main/java/gov/nist/secauto/metaschema/databind/model/binding/metaschema/Property.java
Add support for Metaschema module and constraint property values that are generic strings per metaschema-framework/metaschema#27.
=> Support Metaschema module and constraint string property values

core/src/main/java/gov/nist/secauto/metaschema/core/model/validation/JsonSchemaContentValidator.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/validation/XmlSchemaContentValidator.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/AbstractValidateContentCommand.java
Makes schema validation error a critical validation finding.
Also allows constraint validation to be attempted if the content is not schema valid.
=> Make schema validation errors critical

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/MetapathExpression.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/path/AbstractPathExpression.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/DefaultBoundLoader.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/io/DefaultBoundLoaderTest.java, databind/src/test/resources/content/issue187-instance.xml, databind/src/test/resources/content/issue187-metaschema.xml
Fixed a bug causing non-unique items to be returned in metapaths like `//a//b`.
=> Ensure a double slash Metapath returns unique items

metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/util/LoggingValidationHandler.java
Add the constraint id to the console message if the finding has an associated id.
=> Include constraint id in console output

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnSubstringAfter.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnSubstringAfterTest.java
Implement the `substring-after` function, without collation and three-arg arity variant for #132.
=> Add substring-after impl to Metapath default function registry

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnSubstringBefore.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnSubstringBeforeTest.java
This adds `fn:substring-before()` without collation support for #132.
=> Add `substring-before()` implementation

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnLowerCase.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnUpperCase.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnLowerCaseTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnUpperCaseTest.java
Add lower case and upper case functions, closes #202.
=> Add `lower-case()` and `upper-case()` to Metapath default function registry

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnDocumentAvailable.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnResolveUri.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnDocumentAvailableTest.java
This PR fixes a bug caused when an already absolute or opaque URI is attempted to be resolved, when not necessary.
Typically this will be a no-op, but if the baseUri is not defined in the static context, this will cause an error.
The fix was to check if the URI is already absolute or opaque before attempting to resolve it. When already absolute or opaque, there is no need to resolve it.
Resolves #208.
=> Avoid resolving an already resolved URI in doc-available

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/DefaultItemWriter.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/ConvertContentUsingModuleCommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/MetaschemaCommands.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/ValidateContentUsingModuleCommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/metapath/EvaluateMetapathCommand.java
Enhanced the eval command to output the atomic value of a field or flag.
Also fixed an issue that made the module required, when it should be optional.
=> Eval command improvments

core/pom.xml, core/src/main/antlr4/Metapath10.g4, core/src/main/antlr4/Metapath10Lexer.g4, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/ISequence.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/antlr/Metapath10ParserBase.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/ArraySequenceConstructor.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/BuildCSTVisitor.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/Except.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/path/Axis.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/path/Step.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/impl/StreamSequence.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/IDocumentBasedNodeItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/IModelNodeItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/INodeItem.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/ExpressionTestBase.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/cst/BuildCstVisitorTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/cst/path/StepTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/item/node/MockNodeItemFactory.java, core/src/test/java/gov/nist/secauto/metaschema/core/model/constraint/DefaultConstraintValidatorTest.java, databind/pom.xml, pom.xml
Added preceding, preceding-sibling, following, and following-sibling axis [support in Metapath](https://www.w3.org/TR/xpath-31/#axes).
Also replaced JMock with Mockito for better mocking support.
=> Metapath additional axes

core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/DefaultConstraintValidator.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/IConstraint.java, metaschema-cli/src/test/java/gov/nist/secauto/metaschema/cli/CLITest.java
This PR ensures runtime exceptions are caught that occur during validation.
Resolves metaschema-framework/oscal-cli#67
=> Handle validation runtime errors

cli-processor/src/main/java/gov/nist/secauto/metaschema/cli/processor/CLIProcessor.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/AbstractConvertSubcommand.java, metaschema-cli/src/test/java/gov/nist/secauto/metaschema/cli/CLITest.java
This PR fixes a bug that causes the exit message to be dropped and the CLI tool to exit silently with an error code.
=> Ensure the exit message is not dropped

core/src/test/resources/log4j2-test.xml, databind/src/main/java/gov/nist/secauto/metaschema/databind/AbstractModuleLoaderStrategy.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/DefaultBindingContext.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/PostProcessingModuleLoaderStrategy.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/metaschema/BindingConstraintLoader.java, metaschema-cli/src/test/java/gov/nist/secauto/metaschema/cli/CLITest.java, metaschema-cli/src/test/resources/content/constraint-constraints.xml, metaschema-cli/src/test/resources/content/constraint-example.xml, metaschema-maven-plugin/src/main/java/gov/nist/secauto/metaschema/maven/plugin/AbstractMetaschemaMojo.java
Per pairing session today, this test should validate whether constraint reporting is silently dropping in the latest release.
=> Fix for constraint violation regression

core/src/main/java/gov/nist/secauto/metaschema/core/datatype/AbstractDataTypeAdapter.java, core/src/main/java/gov/nist/secauto/metaschema/core/datatype/IDataTypeAdapter.java, core/src/main/java/gov/nist/secauto/metaschema/core/datatype/adapter/BooleanAdapter.java, core/src/main/java/gov/nist/secauto/metaschema/core/datatype/adapter/DateTimeWithTZAdapter.java, core/src/main/java/gov/nist/secauto/metaschema/core/datatype/adapter/DateWithTZAdapter.java, core/src/main/java/gov/nist/secauto/metaschema/core/datatype/adapter/UuidAdapter.java, core/src/main/java/gov/nist/secauto/metaschema/core/datatype/markup/AbstractMarkupAdapter.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/MetapathExpression.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnData.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnString.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/IDurationItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/IStringItem.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/json/MetaschemaJsonReader.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/json/MetaschemaJsonWriter.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/xml/MetaschemaXmlWriter.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/info/IFeatureScalarItemValueHandler.java
Addressed inconsistent handling of data type parsing calls to provide more consistent error reporting for data type related errors.
Resolves GSA/fedramp-automation#823
=> Improve parser data type error handling

.github/workflows/build.yml, CONTRIBUTING.md
Added some DOs and DONTs related to code review.
=> Add code review advice

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/MetapathExpression.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/antlr/AbstractAstVisitor.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/MetapathExpressionTest.java
Fixed partial metapath parsing, which allowed invalid metapaths to be used if the first part was seen as valid.
Resolves #258
=> Fix partial metapath parse

metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/AbstractValidateContentCommand.java
Delayed registering module to just before constraint validation to ensure schemas are generated directly from the loaded module and not the compiled version.
This issue was caused by the lack for proper choice support in generated bindings. Previous versions of this library used the loaded Metaschema module information directly, without first generating classes for the module. This was changed in the 2.0.0 and 2.0.1 versions. This PR restores the original behavior.
See #262 for follow-on work to fully implement the choice construct in generated bindings.
Resolves #259
=> Restore proper choice behavior in schema generation

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnIndexOf.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnIndexOfTest.java
=> Add `index-of()` function to Metapath default function registry

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnCurrentDate.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnIndexOf.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnIndexOfTest.java
Added the fn:current-date Metapath function in support of #162.
=> Support for fn:current-date

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/InvalidArgumentFunctionException.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/impl/AbstractFunction.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnExactlyOne.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnOneOrMore.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnZeroOrOne.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnExactlyOneTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnOneOrMoreTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnZeroOrOneTest.java
Added support for the Metapath zero-or-one, one-or-more, and exactly-one functions.
Resolves #280
=>  Support for zero-or-one, one-or-more, and exactly-one Metapath functions

metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/util/LoggingValidationHandler.java
Added support for DEBUG level constraints in tool output.
Resolves metaschema-framework/oscal-cli#92
=> Support DEBUG Constraint Level

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnStringJoin.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnStringJoinTest.java
Per discussion this evening, this code addresses some PR feedback missed in #302 for #298 before approval to further simplify, organize, and add some tests tighten up the previous `string-join()` PR.
=> Clean up function signatures and approach for #298

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/DynamicContext.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/StaticContext.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/AbstractExpressionVisitor.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/BuildCSTVisitor.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/CSTPrinter.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/IExpressionVisitor.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/NamedFunctionReference.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/TestUtils.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/cst/BuildCstVisitorTest.java
This PR is related to #283 and supports underlying functions as a prerequisite but does not implement any of the specified functions in that user story.
=> Add named function reference support for other utility operations

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/BuildCSTVisitor.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/cst/AnonymousFunctionCallTest.java
Fixes #320.
- ~Have you included examples of how to use your new feature(s)?~ This is a bug fix, proper usage is addressed in unit tests.
- ~Have you updated all website and readme documentation affected by the changes you made?~ This is a bug fix to the internal implementation of a core processing feature of the parser, and Java docs as written stay the same unless instructed otherwise during PR review.
=> Fix parsing of parameter handling for functions with multiple parameters

metaschema-maven-plugin/src/main/java/gov/nist/secauto/metaschema/maven/plugin/AbstractMetaschemaMojo.java, metaschema-maven-plugin/src/main/java/gov/nist/secauto/metaschema/maven/plugin/GenerateSchemaMojo.java, metaschema-maven-plugin/src/main/java/gov/nist/secauto/metaschema/maven/plugin/GenerateSourcesMojo.java
Refactored Maven generation mojos to more efficiently handle refreshing the IDE (through m2e) for resources that changed. Also ensured that the stale file is created, even when a processing error occurs. This may fix some runaway problems in Eclipse.
=> Efficiently refresh resources changed in generation mojos

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnTimezoneFromDate.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnTimezoneFromDateTime.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnTimezoneFromTime.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnTimezoneFromDateTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnTimezoneFromDateTimeTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnTimezoneFromTimeTest.java
Added `timezone-from-date`, `timezone-from-dateTime`, and `timezone-from-time` Metapath functions and associated unit tests.
Partial work towards #284.
=> date, date/time, and time extraction functions part 1

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnTimezoneFromDate.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnTimezoneFromDateTime.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnTimezoneFromTime.java
Added static methods to make the timezone accessors more consistent with the functions in #275.
=> Add static methods for timezone accessor Metapath functions

core/src/main/java/gov/nist/secauto/metaschema/core/model/xml/XmlMetaConstraintLoader.java
Added missing support for processing let statements in the XMLMetaConstraintLoader.
This is part of a solution for metaschema-framework/liboscal-java#112.
=> Handle let statements in the XmlMetaConstrainLoader

core/src/main/java/gov/nist/secauto/metaschema/core/datatype/DataTypeService.java, schemagen/src/main/java/gov/nist/secauto/metaschema/schemagen/json/impl/AbstractJsonProperty.java, schemagen/src/main/java/gov/nist/secauto/metaschema/schemagen/json/impl/ChoiceGroupInstanceJsonProperty.java, schemagen/src/main/java/gov/nist/secauto/metaschema/schemagen/json/impl/FlagInstanceJsonProperty.java, schemagen/src/main/java/gov/nist/secauto/metaschema/schemagen/json/impl/NamedModelInstanceJsonProperty.java, schemagen/src/main/java/gov/nist/secauto/metaschema/schemagen/json/impl/builder/AbstractCollectionBuilder.java, schemagen/src/main/java/gov/nist/secauto/metaschema/schemagen/json/impl/builder/ArrayBuilder.java
Fixed a bug causing some array schemas to not include a reference to their definition.
Depends on metaschema-framework/metaschema#82.
=> Fix JSON schema generation missing array items

databind/src/main/java/gov/nist/secauto/metaschema/databind/AbstractModuleLoaderStrategy.java
Change the logging level of the matcher replacement warning to debug.
=> Adjust matcher warning to debug

core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/ExternalConstraintsModulePostProcessor.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/IConstraintSet.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/MetaConstraintSet.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/ScopedConstraintSet.java
Localized duplicate constraint application to the constraint context instead of at the post-processor. This should fix a bug where the old behavior is causing some contexts to be ignored.
=> Filter previously applied constraints at the context level
