metaschema-framework/metaschema-java

pom.xml
Updated the jackson and woodstox versions.
=> Bump jackson and woodstox versions

metaschema-cli/src/main/distro/README.txt
Providing better pointers for where to provide feedback and how to find release change information.
=> Improve CLI readme

.lycheeignore, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/AbstractNamedInstanceExpression.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/BuildCSTVisitor.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/path/Flag.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/path/ModelInstance.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/path/Wildcard.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/DefaultConstraintValidator.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/FindingCollectingConstraintValidationHandler.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/IConstraintValidationHandler.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/LoggingConstraintValidationHandler.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/util/JsonUtil.java, databind-metaschema/src/main/java/gov/nist/secauto/metaschema/modules/sarif/SarifValidationHandler.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/ModelDetector.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/json/MetaschemaJsonReader.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/json/MetaschemaJsonUtil.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/annotations/NsBinding.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/binding/metaschema/MetaschemaModuleConstraints.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/metaschema/IBindingDefinitionModel.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/metaschema/IBindingDefinitionModelAssembly.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/metaschema/impl/DefinitionFlagGlobal.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/codegen/BasicMetaschemaTest.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/model/metaschema/BindingModuleLoaderTest.java
This PR fixes a bug which affects GSA/fedramp-automation#622. The bug is caused by improper matching of node names in Metapath queries. Prior changes adjusted the behavior of wildcard processing, but this code was not fully used everywhere. These changes complete implementing the new wildcard matching behavior to correct this bug.
This PR also fixes use of some deprecated APIs and improves the handling of constraint errors to improve debugging.
=> Fix wildcard name matching

.lycheeignore
Ignoring broken documentation links for unsupported dependencies.
=> Ignoring broken documentation links

core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/FindingCollectingConstraintValidationHandler.java, metaschema-maven-plugin/pom.xml
Improved error logging for unexpected constraint validation errors, which were not being logged. This was identified while debugging #101.
Also cleaned up a dependency configuration warning.
=> Ensure unexpected constraint errors are logged

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/RecursionCollectingNodeItemVisitor.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/IModelDefinition.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/INamedModelInstance.java, core/src/main/java/gov/nist/secauto/metaschema/core/util/DefaultDiagramNode.java, core/src/main/java/gov/nist/secauto/metaschema/core/util/IDiagramNode.java, core/src/main/java/gov/nist/secauto/metaschema/core/util/IDiagramNodeVisitor.java, core/src/main/java/gov/nist/secauto/metaschema/core/util/MermaidErDiagramGenerator.java, core/src/main/java/module-info.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/item/node/AbstractRecursionPreventingNodeItemVisitorTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/item/node/RecursionCollectingNodeItemVisitorTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/util/MermaidErDiagramGeneratorTest.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/GenerateDiagramCommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/GenerateSchemaCommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/MetaschemaCommands.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/metapath/EvaluateMetapathCommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/metapath/MetapathCommand.java, metaschema-cli/src/test/java/gov/nist/secauto/metaschema/cli/CLITest.java, metaschema-cli/src/test/java/gov/nist/secauto/metaschema/cli/commands/metapath/EvaluateMetapathSubCommandTest.java, pom.xml
Relocated Mermaid generation code from liboscal-java, so it can be generalized to work with any metaschema module.
To complete this PR, the following needs to be completed:
Resolves #51.
=> Mermaid diagram generation for module

core/pom.xml, core/src/main/java/gov/nist/secauto/metaschema/core/model/validation/XmlSchemaContentValidator.java, metaschema-cli/pom.xml, metaschema-cli/src/main/assembly/bin.xml, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/AbstractValidateContentCommand.java, metaschema-cli/src/main/resources/log4j2.xml, metaschema-cli/src/test/java/gov/nist/secauto/metaschema/cli/CLITest.java, metaschema-cli/src/test/java/gov/nist/secauto/metaschema/cli/commands/metapath/EvaluateMetapathSubCommandTest.java, metaschema-cli/src/test/resources/content/schema-validation-module-missing-required.xml, metaschema-cli/src/test/resources/content/schema-validation-module.xml, pom.xml, schemagen/src/main/java/gov/nist/secauto/metaschema/schemagen/ISchemaGenerator.java, schemagen/src/main/java/gov/nist/secauto/metaschema/schemagen/xml/XmlSchemaGenerator.java
Add the ability to disable schema or constraint validation.
Resolves #113.
=> Support disabling schema and/or constraint validation when validating content 

databind/src/main/java/gov/nist/secauto/metaschema/databind/model/impl/ConstraintFactory.java
Remove the warning around improperly contextualized expression.
=> Remove the warning around improperly contextualized expression.

CONTRIBUTING.md
Closes #123.
- ~Have you written new tests for your core changes, as applicable?~
- ~Have you included examples of how to use your new feature(s)?~
=> Document function registry info

core/src/main/java/gov/nist/secauto/metaschema/core/datatype/markup/AbstractMarkupString.java, core/src/main/java/gov/nist/secauto/metaschema/core/datatype/markup/IMarkupString.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/ConstraintValidationFinding.java, databind-metaschema/pom.xml, databind-metaschema/src/main/java/gov/nist/secauto/metaschema/modules/sarif/SarifValidationHandler.java, databind-metaschema/src/test/java/gov/nist/secauto/metaschema/modules/sarif/SarifValidationHandlerTest.java, databind-metaschema/src/test/resources/sarif-schema-2.1.0.json
Added a junit test to identify problems related to #130.
Adjusted SARIF production to provide a `runs[].tool.driver.rules[].id` and a `runs[].tool.driver.rules[].fullDescription.text` as required by the SARIF JSON schema.
resolves #130
=> Ensure SARIF results are valid to SARIF JSON schema

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnCurrentDateTime.java
Added the current-dateTime metapath function. 
Resolves #164
=> Add the current-dateTime Metapth function

.github/workflows/project.yml
Automatically add a new, reopened, or transferred issue to the project.
=> Auto add issues to project

metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/AbstractConvertSubcommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/ConvertContentUsingModuleCommand.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/MetaschemaCommands.java, metaschema-cli/src/test/java/gov/nist/secauto/metaschema/cli/CLITest.java
Added new convert CLI command.
```
usage: metaschema-cli convert --to=FORMAT -m=FILE_OR_URL [<options>] <source-file-or-URL> [<destination-file>]
-h,--help               display this help message
-m <FILE_OR_URL>        metaschema resource
--no-color           do not colorize output
--overwrite          overwrite the destination if it exists
-q,--quiet              minimize output to include only errors
--show-stack-trace   display the stack trace associated with an error
--to=<FORMAT>        convert to format: xml, json, or yaml
--version            display the application version
```
=> Added new convert metaschema-cli command.

cli-processor/pom.xml, core/pom.xml, databind-metaschema/pom.xml, databind/pom.xml, metaschema-cli/pom.xml, metaschema-maven-plugin/pom.xml, metaschema-testing/pom.xml, pom.xml, schemagen/pom.xml
Bumping version from 1.2.1-SNAPSHOT to 1.3.0-SNAPSHOT, since merged PRs add new features.
=> Feature/bump minor version to 1.3

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnStringLength.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnStringLengthTest.java
=> Add `fn:string-length` to Metapath function registry

core/src/main/java/gov/nist/secauto/metaschema/core/datatype/AbstractDataTypeAdapter.java, core/src/main/java/gov/nist/secauto/metaschema/core/datatype/IDataTypeAdapter.java, core/src/main/java/gov/nist/secauto/metaschema/core/datatype/adapter/BooleanAdapter.java, core/src/main/java/gov/nist/secauto/metaschema/core/datatype/markup/MarkupLineAdapter.java, core/src/main/java/gov/nist/secauto/metaschema/core/datatype/markup/MarkupMultilineAdapter.java, core/src/main/java/gov/nist/secauto/metaschema/core/datatype/markup/flexmark/XmlMarkupParser.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/util/JsonUtil.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/util/XmlEventUtil.java, core/src/test/java/gov/nist/secauto/metaschema/core/datatype/adapter/BooleanAdapterTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/datatype/markup/CommonmarkConformanceTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/datatype/markup/flexmark/MarkupParserTest.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/DefaultBoundLoader.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/IBoundLoader.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/IParsingContext.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/IProblemHandler.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/ModelDetector.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/json/DefaultJsonDeserializer.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/json/DefaultJsonProblemHandler.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/json/IJsonProblemHandler.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/json/MetaschemaJsonReader.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/xml/DefaultXmlDeserializer.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/xml/DefaultXmlProblemHandler.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/io/xml/MetaschemaXmlReader.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/io/Issue206MetaschemaReaderTest.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/io/xml/XmlParserTest.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/model/DefaultAssemblyClassBindingTest.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/model/DefaultFieldPropertyTest.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/ConvertContentUsingModuleCommand.java
Improved parser errors and warnings to include the resource the error  was found in.
=> Improve parser error and warning messages

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/StaticFunctionCall.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/path/Axis.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/IFunction.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/impl/AbstractFunction.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/impl/OperationFunctions.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnDeepEqual.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnIndexOf.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/impl/AbstractArrayItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/impl/AbstractMapItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/impl/AbstractSequence.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/impl/AbstractStringMapKey.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/ICollectionValue.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/IAnyAtomicItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/impl/AbstractUriItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/impl/AnyUriItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/AbstractNodeItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/IAssemblyNodeItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/IDocumentNodeItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/IFeatureAtomicValuedItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/IFeatureNoDataAtomicValuedItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/IFieldNodeItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/IFlagNodeItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/IModuleNodeItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/INodeItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/NodeComparators.java, core/src/main/java/gov/nist/secauto/metaschema/core/qname/IEnhancedQName.java, core/src/main/java/gov/nist/secauto/metaschema/core/qname/QNameCache.java, core/src/main/java/gov/nist/secauto/metaschema/core/util/CustomCollectors.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnDeepEqualTest.java
Added support for the Metapath function [`fn:deep-equal`](https://www.w3.org/TR/xpath-functions-31/#func-deep-equal).
This PR also adds some additional Javadocs for files edited by this PR towards more fully documenting the code base.
=> Metapath `fn:deep-equal` support

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnDistinctValues.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnDistinctValuesTest.java
This PR adds support for the Metapath [fn:distinct-values](https://www.w3.org/TR/xpath-functions-31/#func-distinct-values) function.
=> Metapath `fn:distinct-values` function

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnDocumentUri.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/IDocumentNodeItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/IFieldNodeItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/IFlagNodeItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/DefaultConstraintValidator.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/IAllowedValuesConstraint.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/ICardinalityConstraint.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/IConstraint.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/IExpectConstraint.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/IIndexConstraint.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/IIndexHasKeyConstraint.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/IMatchesConstraint.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/IUniqueConstraint.java, core/src/main/java/gov/nist/secauto/metaschema/core/util/UriUtils.java
Reformatted some code.
Added a type method to IConstraint implementations to provide a human-readable name for the constraint to improve error messages.
=> Code formatting and exception improvements

databind-metaschema/src/main/java/gov/nist/secauto/metaschema/modules/sarif/SarifValidationHandler.java, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/util/LoggingValidationHandler.java
Added SARIF help URIs to console output.
Resolves #276.
=> Add SARIF help uri to console output

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/MapEntry.java
Closes #299.
- ~Have you written new tests for your core changes, as applicable?~
- ~Have you included examples of how to use your new feature(s)?~ This PR includes a bug fix, not a new feature.
- ~Have you updated all website and readme documentation affected by the changes you made?~ This bug fix does not require a documentation change.
=> Fix return type for `map:entry` 

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnStringJoin.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnStringJoinTest.java
Closes #298.
- ~Have you updated all website and readme documentation affected by the changes you made?~ Function documentation is auto-generated from inline comments though.
=> Add implementation of string-join to default function library

core/src/test/java/gov/nist/secauto/metaschema/core/metapath/cst/AnonymousFunctionCallTest.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/codegen/JavaCompilerSupport.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/codegen/ModuleCompilerHelper.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/metaschema/ModuleLoadingPostProcessor.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/model/impl/ConstraintFactoryTest.java, metaschema-maven-plugin/src/main/java/gov/nist/secauto/metaschema/maven/plugin/AbstractMetaschemaMojo.java, metaschema-maven-plugin/src/main/java/gov/nist/secauto/metaschema/maven/plugin/GenerateSchemaMojo.java, metaschema-maven-plugin/src/main/java/gov/nist/secauto/metaschema/maven/plugin/GenerateSourcesMojo.java, pom.xml
Improved the Metaschema module compilation approach used in the schema and code generation mojos to avoid module registration, which was causing compile issues.
=> Improve code and schema generation compilation

cli-processor/src/main/java/gov/nist/secauto/metaschema/cli/processor/AbstractExitStatus.java, cli-processor/src/main/java/gov/nist/secauto/metaschema/cli/processor/ExitStatus.java, cli-processor/src/main/java/gov/nist/secauto/metaschema/cli/processor/NonMessageExitStatus.java, core/pom.xml, core/src/main/java/module-info.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/IFeatureJavaField.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/impl/DefinitionField.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/impl/FieldSupport.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/impl/InstanceFlagInline.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/impl/InstanceModelAssemblyComplex.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/impl/InstanceModelChoiceGroup.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/impl/InstanceModelFieldComplex.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/impl/InstanceModelFieldScalar.java, metaschema-cli/pom.xml, metaschema-cli/src/main/assembly/assembly.xml, metaschema-cli/src/main/assembly/component.xml, metaschema-cli/src/main/assembly/dir.xml, metaschema-cli/src/main/java/gov/nist/secauto/metaschema/cli/commands/AbstractValidateContentCommand.java, pom.xml
- Updated dependencies to newer versions. Cleaned up some unused dependencies.
- Fixed a bug causing a race condition when bound beans are accessed by multiple threads.
- Refactored assembly production to remove a compile warning.
=> Build improvements and race condition fix

core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/ILet.java, databind-metaschema/src/main/java/gov/nist/secauto/metaschema/modules/sarif/SarifValidationHandler.java
According to the SARIF [spec](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790924), `runs.results.locations.logicalLocations` is an array of objects. This was incorrectly represented as a single `logicalLocation`. This PR fixes this.
=> Align use of logicalLocation to SARIF specification

core/src/main/java/gov/nist/secauto/metaschema/core/datatype/adapter/MetaschemaDataTypeProvider.java, core/src/main/java/gov/nist/secauto/metaschema/core/datatype/adapter/QNameAdapter.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/cst/AnonymousFunctionCall.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/CastFunctionException.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/DefaultFunction.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/IFunction.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/DefaultFunctionLibrary.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnFunctionArity.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnFunctionLookup.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnFunctionName.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnQName.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/impl/IFeatureCollectionFunctionItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/IQNameItem.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/atomic/impl/QNameItemImpl.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/TestUtils.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/cst/AnonymousFunctionCallTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/cst/BuildCstVisitorTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnFunctionArityTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnFunctionLookupTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnFunctionNameTest.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnQNameTest.java
Once reviewed and merged if approved, closes #275.
- ~Have you updated all website and readme documentation affected by the changes you made?~ Javadocs are updated via the build pipeline from reading code later.
=> Add Metapath function support functions

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/impl/AbstractFunction.java, core/src/test/java/gov/nist/secauto/metaschema/core/metapath/function/DefaultFunctionTest.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/FnDocTest.java
Tests for function result caching.
=> Test function result caching

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/ModuleNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/ExternalConstraintsModulePostProcessor.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/IConstraintSet.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/MetaConstraintSet.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/ScopedConstraintSet.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/DefaultBindingContext.java
- Cleaned up context processing for meta-constraints. 
- Ensuring the constraint static context is used instead of the module static context.
=> Refactor meta-constraints context handling

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/function/library/FnDoc.java, core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/ModuleNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/ExternalConstraintsModulePostProcessor.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/IConstraintSet.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/MetaConstraintSet.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/ScopedConstraintSet.java
Track the application of constraint sets to a definition to ensure that duplicate constraints are not applied.
=> Avoid duplicate constraints

databind/src/main/java/gov/nist/secauto/metaschema/databind/model/metaschema/binding/METASCHEMA.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/metaschema/binding/MetaschemaMetaConstraints.java, databind/src/main/java/gov/nist/secauto/metaschema/databind/model/metaschema/binding/MetaschemaModuleConstraints.java
Fix syntax error in constraint with hand-coded constraints serialized in Java form. Once reviewed, approved, and merged, it closes #406.
- Have you included examples of how to use your new feature(s)? No, feedback welcome to add tests if necessary.
- ~Have you written new tests for your core changes, as applicable?~
=> Fix constraint #406 syntax error throwing exceptions

core/src/main/java/gov/nist/secauto/metaschema/core/metapath/item/node/ModuleNodeItemImpl.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/AbstractConstraintSet.java, core/src/main/java/gov/nist/secauto/metaschema/core/model/constraint/MetaConstraintSet.java, databind/src/test/java/gov/nist/secauto/metaschema/databind/model/extra/MetaschemaModuleExternalConstraintsTest.java, databind/src/test/resources/content/external-constraint.yml
Refactored the external cosntraints processing to ensure that constraints are applied once per context match.
=> Prevent duplicate external constraint application
